backend:
  name: github
  repo: <% GITHUB_REPOSITORY %> # Gulp will replace this with your GitHub repository
  branch: master # Branch to update (master by default)

media_folder: "site/static/img" # Folder where user uploaded files should go
public_folder: "img"

collections: # A list of collections the CMS should be able to edit
  - name: "post" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Post" # Used in the UI, ie.: "New Post"
    folder: "site/content/post" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    fields: # The fields each document in this collection have
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Intro Blurb", name: "description", widget: "text"}
      - {label: "Image", name: "image", widget: "image", required: false}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "article" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Article" # Used in the UI, ie.: "New Post"
    folder: "site/content/article" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    fields: # The fields each document in this collection have
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Intro Blurb", name: "description", widget: "text"}
      - {label: "Image", name: "image", widget: "image", required: false}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "pages"
    label: "Pages"
    files:
      - file: "site/content/products.md"
        label: "Products Page"
        name: "products"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Type, name: type, widget: hidden, default: products}
          - {label: Page, name: page, widget: hidden, default: "/products.html"}
          - {label: Image, name: image, widget: image}
          - {label: Heading, name: heading, widget: string}
          - {label: Description, name: description, widget: string}
          - {label: Intro, name: intro, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Description, name: description, widget: text}, {label: Blurbs, name: blurbs, widget: list, fields: [{label: Image, name: image, widget: image}, {label: Text, name: text, widget: text}]}]}
          - {label: Main, name: main, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Description, name: description, widget: text}, {label: Image1, name: image1, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}, {label: Image2, name: image2, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}, {label: Image3, name: image3, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}]}
          - {label: Testimonials, name: testimonials, widget: list, fields: [{label: Quote, name: quote, widget: string}, {label: Author, name: author, widget: string}]}
          - {label: Full_image, name: full_image, widget: image}
          - {label: Pricing, name: pricing, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Description, name: description, widget: string}, {label: Plans, name: plans, widget: list, fields: [{label: Plan, name: plan, widget: string}, {label: Price, name: price, widget: string}, {label: Description, name: description, widget: string}, {label: Items, name: items, widget: list}]}]}
  - name: "kitchenSink" # all the things in one entry, for documentation and quick testing
    label: "Kitchen Sink"
    folder: "_sink"
    create: true
    fields:
      - label: "Related Post"
        name: "post"
        widget: "relationKitchenSinkPost"
        collection: "posts"
        searchFields: ["title", "body"]
        valueField: "title"
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Boolean", name: "boolean", widget: "boolean", default: true}
      - {label: "Text", name: "text", widget: "text"}
      - {label: "Number", name: "number", widget: "number"}
      - {label: "Markdown", name: "markdown", widget: "markdown"}
      - {label: "Datetime", name: "datetime", widget: "datetime"}
      - {label: "Date", name: "date", widget: "date"}
      - {label: "Image", name: "image", widget: "image"}
      - {label: "File", name: "file", widget: "file"}
      - {label: "Select", name: "select", widget: "select", options: ["a", "b", "c"]}
      - {label: "Hidden", name: "hidden", widget: "hidden", default: "hidden"}
      - label: "Object"
        name: "object"
        widget: "object"
        fields:
          - label: "Related Post"
            name: "post"
            widget: "relationKitchenSinkPost"
            collection: "posts"
            searchFields: ["title", "body"]
            valueField: "title"
          - {label: "String", name: "string", widget: "string"}
          - {label: "Boolean", name: "boolean", widget: "boolean", default: false}
          - {label: "Text", name: "text", widget: "text"}
          - {label: "Number", name: "number", widget: "number"}
          - {label: "Markdown", name: "markdown", widget: "markdown"}
          - {label: "Datetime", name: "datetime", widget: "datetime"}
          - {label: "Date", name: "date", widget: "date"}
          - {label: "Image", name: "image", widget: "image"}
          - {label: "File", name: "file", widget: "file"}
          - {label: "Select", name: "select", widget: "select", options: ["a", "b", "c"]}
      - label: "List"
        name: "list"
        widget: "list"
        fields:
          - {label: "String", name: "string", widget: "string"}
          - {label: "Boolean", name: "boolean", widget: "boolean"}
          - {label: "Text", name: "text", widget: "text"}
          - {label: "Number", name: "number", widget: "number"}
          - {label: "Markdown", name: "markdown", widget: "markdown"}
          - {label: "Datetime", name: "datetime", widget: "datetime"}
          - {label: "Date", name: "date", widget: "date"}
          - {label: "Image", name: "image", widget: "image"}
          - {label: "File", name: "file", widget: "file"}
          - {label: "Select", name: "select", widget: "select", options: ["a", "b", "c"]}
          - label: "Object"
            name: "object"
            widget: "object"
            fields:
              - {label: "String", name: "string", widget: "string"}
              - {label: "Boolean", name: "boolean", widget: "boolean"}
              - {label: "Text", name: "text", widget: "text"}
              - {label: "Number", name: "number", widget: "number"}
              - {label: "Markdown", name: "markdown", widget: "markdown"}
              - {label: "Datetime", name: "datetime", widget: "datetime"}
              - {label: "Date", name: "date", widget: "date"}
              - {label: "Image", name: "image", widget: "image"}
              - {label: "File", name: "file", widget: "file"}
              - {label: "Select", name: "select", widget: "select", options: ["a", "b", "c"]}
              - label: "List"
                name: "list"
                widget: "list"
                fields:
                  - label: "Related Post"
                    name: "post"
                    widget: "relationKitchenSinkPost"
                    collection: "posts"
                    searchFields: ["title", "body"]
                    valueField: "title"
                  - {label: "String", name: "string", widget: "string"}
                  - {label: "Boolean", name: "boolean", widget: "boolean"}
                  - {label: "Text", name: "text", widget: "text"}
                  - {label: "Number", name: "number", widget: "number"}
                  - {label: "Markdown", name: "markdown", widget: "markdown"}
                  - {label: "Datetime", name: "datetime", widget: "datetime"}
                  - {label: "Date", name: "date", widget: "date"}
                  - {label: "Image", name: "image", widget: "image"}
                  - {label: "File", name: "file", widget: "file"}
                  - {label: "Select", name: "select", widget: "select", options: ["a", "b", "c"]}
                  - {label: "Hidden", name: "hidden", widget: "hidden", default: "hidden"}
                  - label: "Object"
                    name: "object"
                    widget: "object"
                    fields:
                      - {label: "String", name: "string", widget: "string"}
                      - {label: "Boolean", name: "boolean", widget: "boolean"}
                      - {label: "Text", name: "text", widget: "text"}
                      - {label: "Number", name: "number", widget: "number"}
                      - {label: "Markdown", name: "markdown", widget: "markdown"}
                      - {label: "Datetime", name: "datetime", widget: "datetime"}
                      - {label: "Date", name: "date", widget: "date"}
                      - {label: "Image", name: "image", widget: "image"}
                      - {label: "File", name: "file", widget: "file"}
                      - {label: "Select", name: "select", widget: "select", options: ["a", "b", "c"]}
